config/routes.rb
Rails.application.routes.draw do
  resources :blogs do
    collection do
      post :confirm
    end
  end  
  root to: 'blogs#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true,length: { in: 1..140 }
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  
  def index
   @blogs = Blog.all
  end
  
  def new
    
    if params[:back]
      @blog = Blog.new(blogs_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blogs_params)
    if @blog.save
      # 一覧画面へ遷移して"ブログを作成しました！"とメッセージを表示します。
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      # 入力フォームを再描画します。
      render 'new'
    end
  end

  def show
    @Blog = Blog.find(params[:id])
  end
  
  def edit
    @Blog = Blog.find(params[:id])
  end

  def destroy
    @blog.destroy
    redirect_to blogs_path, notice:"ブログを削除しました！"
  end
  
  def confirm
    @blog = Blog.new(blogs_params)
    render :new if @blog.invalid?
  end
  
  def update
    @blog = Blog.find(params[:id])
    if @blog.update(blogs_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  private
  def blogs_params
    params.require(:blog).permit(:title, :content)
  end
  
      # idをキーとして値を取得するメソッド
  def set_blog
      @blog = Blog.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, url: confirm_blogs_path, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>
        <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

<%= link_to "ブログ一覧画面にもどる", blogs_path %>

app/views/blogs/confirm.html.erb
<h3>以下の内容で、送信する。</h3>

<%= form_for(@blog) do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <p>タイトル!:<%= @blog.title %></p>
  <p>本文!:<%= @blog.content %></p>
  <%= f.submit "登録する" %>
<% end %>

<%= form_for(@blog, url: new_blog_path, method: 'get') do |f| %>
  <%= f.hidden_field :title %>
  <%= f.hidden_field :content %>
  <%= f.submit "もどる" %>
<% end %>

app/views/blogs/edit.html.erb
<%= form_with(model: @blog, local: true) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります!!!</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="blog_title">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>
  <div class="blog_title">
    <%= form.label :content %>
    <%= form.text_field :content %>
  </div>
  <%= form.submit %>
<% end %>

app/views/blogs/index.html.erb
<h1>ブログ一覧</h1>

<table>
  <tr>
    <th>タイトル</th>
    <th>内容</th></th>
  </tr>

<% @blogs.each do |blog| %>
  <tr>
    <td><%= blog.title %></td>
    <td><%= blog.content %></td>
    <td><%= link_to "ブログを編集する!", edit_blog_path(blog.id), data:{ confirm:'本当に編集していいですか？'} %></td>
    <td><%= link_to 'ブログを削除する!', blog_path(blog.id), method: :delete, data:{ confirm:'本当に削除して良いですか？'} %></td>
  </tr>
<% end %>
</table>

<br>

<%= link_to '新しくブログを投稿する', new_blog_path %>

app/views/blogs/new.html.erb
<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>KadaiBlog</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>